"""Deterministic slug normalization for aviation entities."""

from __future__ import annotations

import re
import unicodedata


def normalize_airline_slug(name: str) -> str:
    """Convert airline name to canonical slug.

    Examples:
        "British Airways" -> "british-airways"
        "LATAM Airlines Brasil" -> "latam-airlines-brasil"
        "Air France–KLM" -> "air-france-klm"
        "Türk Hava Yolları" -> "turk-hava-yollari"
    """
    text = unicodedata.normalize("NFKD", name)
    text = text.encode("ascii", "ignore").decode("ascii")
    text = text.lower().strip()
    text = re.sub(r"[^\w\s-]", "", text)
    text = re.sub(r"[\s_]+", "-", text)
    text = re.sub(r"-+", "-", text)
    return text.strip("-")


COUNTRY_TO_REGION: dict[str, str] = {
    "Afghanistan": "Asia",
    "Albania": "Europe",
    "Algeria": "Africa",
    "Angola": "Africa",
    "Argentina": "Latin America",
    "Armenia": "Asia",
    "Australia": "Oceania",
    "Austria": "Europe",
    "Azerbaijan": "Asia",
    "Bahamas": "Latin America",
    "Bahrain": "Middle East",
    "Bangladesh": "Asia",
    "Barbados": "Latin America",
    "Belarus": "Europe",
    "Belgium": "Europe",
    "Belize": "Latin America",
    "Benin": "Africa",
    "Bermuda": "North America",
    "Bhutan": "Asia",
    "Bolivia": "Latin America",
    "Bosnia and Herzegovina": "Europe",
    "Botswana": "Africa",
    "Brazil": "Latin America",
    "Brunei": "Asia",
    "Bulgaria": "Europe",
    "Burkina Faso": "Africa",
    "Cambodia": "Asia",
    "Cameroon": "Africa",
    "Canada": "North America",
    "Cape Verde": "Africa",
    "Cayman Islands": "Latin America",
    "Chad": "Africa",
    "Chile": "Latin America",
    "China": "Asia",
    "Colombia": "Latin America",
    "Comoros": "Africa",
    "Congo": "Africa",
    "Costa Rica": "Latin America",
    "Croatia": "Europe",
    "Cuba": "Latin America",
    "Cyprus": "Europe",
    "Czech Republic": "Europe",
    "Czechia": "Europe",
    "Denmark": "Europe",
    "Dominican Republic": "Latin America",
    "DR Congo": "Africa",
    "Ecuador": "Latin America",
    "Egypt": "Africa",
    "El Salvador": "Latin America",
    "Equatorial Guinea": "Africa",
    "Eritrea": "Africa",
    "Estonia": "Europe",
    "Ethiopia": "Africa",
    "Fiji": "Oceania",
    "Finland": "Europe",
    "France": "Europe",
    "Gabon": "Africa",
    "Gambia": "Africa",
    "Georgia": "Europe",
    "Germany": "Europe",
    "Ghana": "Africa",
    "Greece": "Europe",
    "Guatemala": "Latin America",
    "Guinea": "Africa",
    "Honduras": "Latin America",
    "Hong Kong": "Asia",
    "Hungary": "Europe",
    "Iceland": "Europe",
    "India": "Asia",
    "Indonesia": "Asia",
    "Iran": "Middle East",
    "Iraq": "Middle East",
    "Ireland": "Europe",
    "Israel": "Middle East",
    "Italy": "Europe",
    "Ivory Coast": "Africa",
    "Jamaica": "Latin America",
    "Japan": "Asia",
    "Jordan": "Middle East",
    "Kazakhstan": "Asia",
    "Kenya": "Africa",
    "Korea": "Asia",
    "South Korea": "Asia",
    "Kuwait": "Middle East",
    "Kyrgyzstan": "Asia",
    "Laos": "Asia",
    "Latvia": "Europe",
    "Lebanon": "Middle East",
    "Libya": "Africa",
    "Lithuania": "Europe",
    "Luxembourg": "Europe",
    "Macau": "Asia",
    "Madagascar": "Africa",
    "Malawi": "Africa",
    "Malaysia": "Asia",
    "Maldives": "Asia",
    "Mali": "Africa",
    "Malta": "Europe",
    "Mauritania": "Africa",
    "Mauritius": "Africa",
    "Mexico": "Latin America",
    "Moldova": "Europe",
    "Mongolia": "Asia",
    "Montenegro": "Europe",
    "Morocco": "Africa",
    "Mozambique": "Africa",
    "Myanmar": "Asia",
    "Namibia": "Africa",
    "Nepal": "Asia",
    "Netherlands": "Europe",
    "New Zealand": "Oceania",
    "Nicaragua": "Latin America",
    "Niger": "Africa",
    "Nigeria": "Africa",
    "North Macedonia": "Europe",
    "Norway": "Europe",
    "Oman": "Middle East",
    "Pakistan": "Asia",
    "Palestine": "Middle East",
    "Panama": "Latin America",
    "Papua New Guinea": "Oceania",
    "Paraguay": "Latin America",
    "Peru": "Latin America",
    "Philippines": "Asia",
    "Poland": "Europe",
    "Portugal": "Europe",
    "Puerto Rico": "Latin America",
    "Qatar": "Middle East",
    "Romania": "Europe",
    "Russia": "Europe",
    "Rwanda": "Africa",
    "Saudi Arabia": "Middle East",
    "Senegal": "Africa",
    "Serbia": "Europe",
    "Seychelles": "Africa",
    "Sierra Leone": "Africa",
    "Singapore": "Asia",
    "Slovakia": "Europe",
    "Slovenia": "Europe",
    "Solomon Islands": "Oceania",
    "Somalia": "Africa",
    "South Africa": "Africa",
    "Spain": "Europe",
    "Sri Lanka": "Asia",
    "Sudan": "Africa",
    "Suriname": "Latin America",
    "Sweden": "Europe",
    "Switzerland": "Europe",
    "Syria": "Middle East",
    "Taiwan": "Asia",
    "Tajikistan": "Asia",
    "Tanzania": "Africa",
    "Thailand": "Asia",
    "Togo": "Africa",
    "Trinidad and Tobago": "Latin America",
    "Tunisia": "Africa",
    "Turkey": "Europe",
    "Turkmenistan": "Asia",
    "Uganda": "Africa",
    "Ukraine": "Europe",
    "United Arab Emirates": "Middle East",
    "United Kingdom": "Europe",
    "United States": "North America",
    "Uruguay": "Latin America",
    "Uzbekistan": "Asia",
    "Vanuatu": "Oceania",
    "Venezuela": "Latin America",
    "Vietnam": "Asia",
    "Yemen": "Middle East",
    "Zambia": "Africa",
    "Zimbabwe": "Africa",
}


def resolve_region(country: str | None) -> str | None:
    """Map country to operational region using canonical deterministic mapping."""
    if not country:
        return None
    return COUNTRY_TO_REGION.get(country)
