"""Aviation Knowledge Graph models — nodes, edges, and fusion signals."""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any
from uuid import uuid4

from sqlalchemy import DateTime, Float, Index, Integer, String, Text, UniqueConstraint
from sqlalchemy import text as sql_text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column

from database.models.base import TimestampMixin
from database.session import Base


class GraphNode(TimestampMixin, Base):
    """A node in the aviation knowledge graph (airline, airport, route, etc.)."""

    __tablename__ = "graph_nodes"
    __table_args__ = (
        UniqueConstraint("node_type", "entity_id", name="uq_graph_node_type_entity"),
        Index("ix_graph_nodes_type", "node_type"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=lambda: str(uuid4()))
    node_type: Mapped[str] = mapped_column(String(40), nullable=False)
    entity_id: Mapped[str] = mapped_column(String(180), nullable=False)
    label: Mapped[str] = mapped_column(String(300), nullable=False)
    properties: Mapped[dict[str, Any]] = mapped_column(
        JSONB,
        default=dict,
        server_default=sql_text("'{}'::jsonb"),
        nullable=False,
    )
    mention_count: Mapped[int] = mapped_column(
        Integer,
        default=0,
        server_default=sql_text("0"),
        nullable=False,
    )


class GraphEdge(TimestampMixin, Base):
    """A directed relationship between two graph nodes."""

    __tablename__ = "graph_edges"
    __table_args__ = (
        UniqueConstraint("source_node_id", "target_node_id", "edge_type", name="uq_graph_edge"),
        Index("ix_graph_edges_type", "edge_type"),
        Index("ix_graph_edges_source", "source_node_id"),
        Index("ix_graph_edges_target", "target_node_id"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=lambda: str(uuid4()))
    source_node_id: Mapped[str] = mapped_column(String(36), nullable=False)
    target_node_id: Mapped[str] = mapped_column(String(36), nullable=False)
    edge_type: Mapped[str] = mapped_column(String(60), nullable=False)
    weight: Mapped[float] = mapped_column(Float, default=1.0, nullable=False)
    properties: Mapped[dict[str, Any]] = mapped_column(
        JSONB,
        default=dict,
        server_default=sql_text("'{}'::jsonb"),
        nullable=False,
    )


class FusionSignal(TimestampMixin, Base):
    """A strategic intelligence signal generated by the fusion engine."""

    __tablename__ = "fusion_signals"
    __table_args__ = (
        Index("ix_fusion_signals_category", "category"),
        Index("ix_fusion_signals_severity", "severity"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=lambda: str(uuid4()))
    category: Mapped[str] = mapped_column(String(60), nullable=False)
    severity: Mapped[str] = mapped_column(String(20), nullable=False)
    title: Mapped[str] = mapped_column(String(500), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    entities: Mapped[list[str]] = mapped_column(
        JSONB,
        default=list,
        server_default=sql_text("'[]'::jsonb"),
        nullable=False,
    )
    evidence: Mapped[dict[str, Any]] = mapped_column(
        JSONB,
        default=dict,
        server_default=sql_text("'{}'::jsonb"),
        nullable=False,
    )
    confidence: Mapped[float] = mapped_column(Float, default=0.5, nullable=False)
    detected_at: Mapped[datetime] = mapped_column(
        DateTime,
        default=lambda: datetime.now(timezone.utc),
        server_default=sql_text("now()"),
        nullable=False,
    )
    is_active: Mapped[bool] = mapped_column(default=True, server_default=sql_text("true"), nullable=False)


class ReviewIntelligence(TimestampMixin, Base):
    """Structured intelligence extracted from a single review."""

    __tablename__ = "review_intelligence"
    __table_args__ = (
        Index("ix_review_intel_review", "review_id"),
        Index("ix_review_intel_severity", "operational_severity"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=lambda: str(uuid4()))
    review_id: Mapped[str] = mapped_column(String(36), unique=True, nullable=False)
    disruptions: Mapped[dict[str, Any]] = mapped_column(
        JSONB,
        default=dict,
        server_default=sql_text("'{}'::jsonb"),
        nullable=False,
    )
    quality_scores: Mapped[dict[str, Any]] = mapped_column(
        JSONB,
        default=dict,
        server_default=sql_text("'{}'::jsonb"),
        nullable=False,
    )
    aircraft_mentions: Mapped[list[str]] = mapped_column(
        JSONB,
        default=list,
        server_default=sql_text("'[]'::jsonb"),
        nullable=False,
    )
    route_mentions: Mapped[list[dict]] = mapped_column(
        JSONB,
        default=list,
        server_default=sql_text("'[]'::jsonb"),
        nullable=False,
    )
    airport_mentions: Mapped[list[str]] = mapped_column(
        JSONB,
        default=list,
        server_default=sql_text("'[]'::jsonb"),
        nullable=False,
    )
    operational_severity: Mapped[str] = mapped_column(String(20), default="low", nullable=False)
    intelligence_data: Mapped[dict[str, Any]] = mapped_column(
        JSONB,
        default=dict,
        server_default=sql_text("'{}'::jsonb"),
        nullable=False,
    )
